// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ro80oVB-dRApLC41zveqalegdKZPjco',
    appId: '1:556324282884:android:e946595533356224d1cb51',
    messagingSenderId: '556324282884',
    projectId: 'gameshowbuzzer-cfe32',
    storageBucket: 'gameshowbuzzer-cfe32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOxuTX495Sbsue-cpntZF6yFr7kyWfWxA',
    appId: '1:556324282884:ios:e5347543212c1114d1cb51',
    messagingSenderId: '556324282884',
    projectId: 'gameshowbuzzer-cfe32',
    storageBucket: 'gameshowbuzzer-cfe32.appspot.com',
    iosClientId: '556324282884-4arsuolhhpa11ebalvt1j3gtj5e19igj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameShowBuzzer',
  );
}
